version: '3.4'

services:

  trendyol.linkconverter.api:
   image: ${DOCKER_REGISTRY-}trendyollinkconverterapi
   build:
     context: .
     dockerfile: Trendyol.LinkConverter.Api/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1

  redis:
    image: redis:alpine

volumes:
    elasticsearch-data: